
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-7pm-2
owner: ucsb-cs156-s23
repo_name: team03-s23-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjgzNTc5MTY=","is_bot":false,"login":"Arik","name":""},"headRefName":"restaurantFrontendUsesBackend","number":28,"title":"Restaurant frontend uses backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-2/pull/28"},{"author":{"id":"MDQ6VXNlcjgzNTc5MTY=","is_bot":false,"login":"Arik","name":""},"headRefName":"Arik-FixAppJS","number":27,"title":"Fix App.js","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-2/pull/27"},{"author":{"id":"U_kgDOBXu4sA","is_bot":false,"login":"ColinBaylis","name":""},"headRefName":"Colin-restaurantFrontend","number":26,"title":"Colin restaurant frontend","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-2/pull/26"}]
