
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-7pm-2
owner: ucsb-cs156-s23
repo_name: team03-s23-7pm-2
pull_requests: [{"author":{"id":"U_kgDOBtJaVA","is_bot":false,"login":"NateHoang","name":"Nathan Hoang"},"headRefName":"nh-frontendRest","number":19,"title":"Finished nh-frontendRest as everything works","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-2/pull/19"},{"author":{"id":"U_kgDOBbLB7w","is_bot":false,"login":"maya-maye","name":""},"headRefName":"mm-copySchoolFrontend","number":18,"title":"mm-added all school frontend","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-2/pull/18"}]
