
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-7pm-2
owner: ucsb-cs156-s23
repo_name: team03-s23-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjY0Mzg1Mzgw","is_bot":false,"login":"justinthecao","name":"Justin Cao"},"headRefName":"jc-school-crud","number":16,"title":"Jc school crud","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-2/pull/16"},{"author":{"id":"U_kgDOBtJaVA","is_bot":false,"login":"NateHoang","name":"Nathan Hoang"},"headRefName":"nh-backendRest","number":15,"title":"Added the files for restaurant from team02 into team03","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-2/pull/15"},{"author":{"id":"MDQ6VXNlcjcyODQyMzEy","is_bot":false,"login":"JNewman-cell","name":"Jackson Newman"},"headRefName":"LaptopFrontend","number":14,"title":"jn-added frontend laptop files","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-2/pull/14"},{"author":{"id":"MDQ6VXNlcjgzNTc5MTY=","is_bot":false,"login":"Arik","name":""},"headRefName":"Arik-LaptopBackend","number":13,"title":"Add Laptop Backend","url":"https://github.com/ucsb-cs156-s23/team03-s23-7pm-2/pull/13"}]
